
slice_service:
  sfa:
    authority_list: https://flsmonitor.fed4fire.eu/testbeds.xml
    clearing_house: https://ch.geni.net/SA
    member_authority: https://ch.geni.net/MA

    x509:
#      cert: certs/urn:publicid:IDN+ch.geni.net+tool+job_service.testing.local.pem
#      key: certs/testing.local.key
#      ca: certs/trusted_roots.pem
#
#      cert: /Users/max/.gcf/max-geni.key.cert
#      key: /Users/max/.gcf/max-geni.key.cert
#      ca: /Users/max/.gcf/trusted_roots/GPO.crt
#
      cert: certs/testing.local.key
      key: certs/testing.local.key
      ca: certs/trusted_roots.crt

  init_script:
    frcp: amqp://srv.mytestbed.net
    oml_collect_uri: tcp:srv.mytestbed.net:3004
    top_dir: /var/lib/slice_service

